### ISSUE TITLE
设置上下居中后出现这种情况

### ISSUE THREAD

**Issue by dtt-android** [Leo199206/SideBar#1]
![image](https://user-images.githubusercontent.com/15831485/125580271-433eaba5-f152-4792-b361-8b6eb0be36ab.png)

**Comment by dtt-android** [comment]
控件高设置match_parent和wrap_content时onMeasure里itemStartY的值不一样

**Comment by Leo199206** [comment]
@15021585823  我用demo试过高度设置match_parent和wrap_content都是没有问题的。建议检查下控件在项目布局中的用法，看看和demo有哪些不一样。

**Comment by Leo199206** [comment]
没有其他反馈，先关了
